# Generated by Django 4.0.1 on 2022-01-04 23:44

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
